# Dockerfile.airflow
FROM apache/airflow:2.9.3

# Add minimal OS tools
USER root
RUN apt-get update && apt-get install -y --no-install-recommends curl git && \
    rm -rf /var/lib/apt/lists/*

# Install DVC (HTTP/Dagshub flavor; use [s3] if you plan S3)
USER airflow
RUN pip install --no-cache-dir "dvc[http]==3.58.0" \
    pandas==2.1.4 scikit-learn==1.5.2 joblib==1.4.2 mlflow>=2.12,<3 \
    pyyaml==6.0.1 dagshub==0.3.13
